import { describe, expect, it } from 'vitest';
import { createDefaultProject, createPanoAsset, createPanoReference, createProjectionRegion, createProjectionRegionAlignment, createProjectionRegionVertexPair } from '../src/domain/defaults';
import { projectionRegionDiagnosticsForAlignment, projectionRegionDiagnosticsForProject } from '../src/engine/projectionRegionDiagnostics';

function fixture() { const project = createDefaultProject(); const grayAsset = createPanoAsset({ name: 'gray', uri: 'gray', width: 100, height: 50 }); const styleAsset = createPanoAsset({ name: 'style', uri: 'style', width: 100, height: 50 }); project.assets.assets[grayAsset.id] = grayAsset; project.assets.assets[styleAsset.id] = styleAsset; const gray = createPanoReference({ name: 'Gray', assetId: grayAsset.id, type: 'graybox_render', origin: [0, 0, 0], width: 100, height: 50 }); const style = createPanoReference({ name: 'Style', assetId: styleAsset.id, type: 'ai_global_reference', origin: [0, 0, 0], width: 100, height: 50 }); project.panoRefs = [gray, style]; const points: [number, number][] = [[0.45, 0.45], [0.55, 0.45], [0.55, 0.55], [0.45, 0.55]]; const region = createProjectionRegion(points.map((point, index) => createProjectionRegionVertexPair(point, point, `v${index}`))); return { project, gray, style, region, alignment: createProjectionRegionAlignment(style.id, gray.id, [region]) }; }
describe('Region Fit diagnostics', () => {
  it('reports none and ready without acquiring textures', () => { const { project, alignment, style } = fixture(); expect(projectionRegionDiagnosticsForProject(project, style.id).status).toBe('none'); expect(projectionRegionDiagnosticsForAlignment(project, alignment)).toMatchObject({ status: 'ready', message: '1 region', valid: true }); });
  it('reports incomplete, stale, and origin mismatch', () => { const { project, alignment, style } = fixture(); alignment.regions[0].vertices.pop(); alignment.regions[0].vertices.pop(); expect(projectionRegionDiagnosticsForAlignment(project, alignment).status).toBe('incomplete'); alignment.regions = []; alignment.sourcePanoId = 'missing'; expect(projectionRegionDiagnosticsForAlignment(project, alignment).status).toBe('stale'); const next = fixture(); next.style.origin = [0.3, 0, 0]; expect(projectionRegionDiagnosticsForAlignment(next.project, next.alignment).status).toBe('origin-mismatch'); });
  it('reports self intersections, oversized regions, and foldovers', () => { const self = fixture(); self.alignment.regions[0].vertices[1].targetUv = [0.55, 0.55]; self.alignment.regions[0].vertices[2].targetUv = [0.55, 0.45]; expect(projectionRegionDiagnosticsForAlignment(self.project, self.alignment).status).toBe('self-intersecting'); const large = fixture(); large.alignment.regions[0].vertices = [[0.1, 0.5], [0.5, 0.4], [0.9, 0.5]].map((point, index) => createProjectionRegionVertexPair(point as [number, number], point as [number, number], `l${index}`)); expect(projectionRegionDiagnosticsForAlignment(large.project, large.alignment).status).toBe('too-large'); const fold = fixture(); fold.alignment.regions[0].vertices.forEach((vertex, index) => { vertex.sourceUv = [[0.45, 0.45], [0.45, 0.55], [0.55, 0.55], [0.55, 0.45]][index] as [number, number]; }); expect(projectionRegionDiagnosticsForAlignment(fold.project, fold.alignment).status).toBe('folded'); });
});
